spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false
    username: root
    password: root
    hikari:
      minimum-idle: 3
      maximum-pool-size: 5
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    br.com.ecommerce: debug